# Generated by Django 3.2.10 on 2022-02-04 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='usertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=30)),
                ('companyid', models.CharField(max_length=30)),
                ('bankholder', models.CharField(max_length=30)),
                ('bankaccountnumber', models.CharField(max_length=30)),
                ('bankaccountifsc', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=300)),
                ('mobile', models.BigIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('requestdate', models.DateField(default=django.utils.timezone.now)),
                ('otp', models.IntegerField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileapp.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.BigIntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('address', models.TextField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('otp', models.IntegerField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileapp.usertype')),
            ],
        ),
    ]
