# Generated by Django 3.2.10 on 2022-02-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], max_length=20)),
            ],
        ),
    ]
