# Generated by Django 3.2.10 on 2022-02-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomadmin', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.BigIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='ecomadmin.role'),
        ),
    ]
